services:
  - docker

install:
  - docker build -t impressioner --target test .

script:
  - docker run -e "MIX_ENV=test" --rm -it impressioner mix test
  - docker run -e "MIX_ENV=test" --rm -it impressioner mix format --check-formatted
