services:
  - docker

install:
  - docker build -t impressioner .

script:
  - docker run -e "MIX_ENV=test" --rm -it impressioner mix test
  - docker run -e "MIX_ENV=test" --rm -it impressioner mix format --check-formatted
  - docker run -e "NODE_ENV=development" --rm -it impressioner npm run eslint
