version: "3"

services:
  web:
    build: .
    image: impressioner/web
    ports:
      - "4000:4000"
    volumes: &web-volumes
      - ./:/app
      - /priv/static/
    environment: &web-environment
      MIX_ENV: null
      NODE_ENV: development
      POSTGRESQL_HOST: db

  webpack:
    build: .
    image: impressioner/web
    volumes: *web-volumes
    command: npm run watch
    environment: *web-environment
