version: "3"

services:
  web:
    build:
      context: .
      target: dev
    image: impressioner/web
    ports:
      - "4000:4000"
    volumes: &web-volumes
      - ./:/app
      - /priv/static/
    environment: &web-environment
      MIX_ENV: null
      NODE_ENV: development
      POSTGRESQL_HOST: db
    user: '1000:1000'
